### ISSUE TITLE
Error on CYS

### ISSUE THREAD

**Issue by joaomcteixeira** [DeepRank/pdbprep#9]
Hi @DaniBodor @DarioMarzella 

Following our discussion the other day, here is PDB that gives an error with the cysteine. I haven't inspected thoroughly to trace the source of the error.

```
· run_pdbprep.sh pdblist 
performing with 1 CPUS..
processing 7AYE...
Traceback (most recent call last):
  File "/home/joao/github/pdbprep/add_ff_hydrogens.py", line 45, in <module>
    model.addHydrogens(forcefield=forcefield, variants=protonated_sequence)
  File "/home/joao/anaconda3/envs/openmm/lib/python3.11/site-packages/openmm/app/modeller.py", line 998, in addHydrogens
    system = forcefield.createSystem(newTopology, rigidWater=False, nonbondedMethod=CutoffNonPeriodic)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joao/anaconda3/envs/openmm/lib/python3.11/site-packages/openmm/app/forcefield.py", line 1218, in createSystem
    templateForResidue = self._matchAllResiduesToTemplates(data, topology, residueTemplates, ignoreExternalBonds)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joao/anaconda3/envs/openmm/lib/python3.11/site-packages/openmm/app/forcefield.py", line 1433, in _matchAllResiduesToTemplates
    raise ValueError('No template found for residue %d (%s).  %s  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 121 (CYS).  The set of atoms matches CYS, but the bonds are different.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
all done
```

**Comment by DaniBodor** [comment]
thanks for leaving this comment. It's a good starting point when we want to implement it in deeprank2
